[features]
seeds = false
skip-lint = false
[programs.localnet]
e_signature = "EqsfiqKZqSVk6r8mMBSsad6hMaYxy1pLqkfG2w6St9Yf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ryan/.config/solana/id.json"

[scripts]
test = "yarn run test"
