[features]
seeds = false
skip-lint = false
[programs.localnet]
e_signature = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ryan/.config/solana/id.json"

[scripts]
test = "yarn run test"
