[features]
seeds = false
skip-lint = false
[programs.localnet]
e_signature = "FqUDkQ5xq2XE7BecTN8u9R28xtLudP7FgCTC8vSLDEwL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ryan/.config/solana/id.json"

[scripts]
test = "yarn run test"
